package i4U.mukPic.user.entity;

public enum AllergyType {
    PEANUTS, SHELLFISH, DAIRY, EGGS, FISH,
    CRAB, SHRIMP, SQUID, ABALONE, MUSSEL, OYSTER, PEACH, TOMATO,
    BUCK_WHEAT, WHEAT, WALNUT, PINE_NUT, SOYBEAN, PORK, MILK, CHICKEN, BEEF, SULFUROUS;

}
