package i4U.mukPic.user.entity;

public enum DietaryPreferenceType {
    VEGAN, HALAL, VEGETARIAN, KOSHER, NO_FOOD_TO_COVER, PESCATARIAN, LOW_SPICE_TOLERANCE,
    NO_ALCOHOL, GLUTEN_FREE, LACTOSE_FREE, LOW_CARB;

}
