spring:
  profiles:
    default: local

cloud:
  aws:
    s3:
      bucket: mukpic-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}