spring:
  application:
    name: mukPic
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: profile, email
  sql:
    init:
      mode: always
      data-locations:
        - classpath:data.sql

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework: debug


cloud:
  aws:
    s3:
      bucket: mukpic-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    expiration-time: 2592000000 # 30 days in milliseconds
  refresh:
    expiration-time: 2592000000 # 30 days in milliseconds


openai:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: ${OPENAI_SECRET_KEY}