spring:
  application:
    name: mukPic
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: profile, email

  sql:
    init:
      data-locations:
        - classpath:data.sql

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework: debug


cloud:
  aws:
    s3:
      bucket: mukpic-image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    expiration-time: 3600000 # 1 hour in milliseconds
  refresh:
    expiration-time: 1209600000 #2주

openai:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: ${OPENAI_SECRET_KEY}