name: Server Deploy

on:
  push:
    branches:
      - dev
    paths:
      - 'mukpic/**'

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        working-directory: ./server
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./server
        run: ./gradlew build

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Docker build and push
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          cd server
          docker build -t mukpic-server .
          docker tag mukpic-server $DOCKER_HUB_USERNAME/mukpic-server:v1
          docker push $DOCKER_HUB_USERNAME/mukpic-server:v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Restart Docker container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^mukpic-server$'; then
            docker stop mukpic-server
            docker rm mukpic-server
          fi
          docker run -d --name mukpic-server -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/mukpic-server:v1
