name: Server Deploy

on:
  push:
    branches:
      - dev
    paths:
      - 'mukpic/**'

jobs:
  server:
    runs-on: self-hosted
    
    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        working-directory: ./mukpic
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./mukpic
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          cd mukpic
          docker build -t mukpic-server .
          docker tag mukpic-server ${{secrets.DOCKER_HUB_USERNAME}}/mukpic-server:v1
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/mukpic-server:v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Check if container exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^mukpic-server$'; then
            docker rm -f mukpic-server
          fi
        continue-on-error: true

      - name: Run scripts in server
        uses: appleboy/ssh-action@v0.1.16
        with:
          key: ${{secrets.EC2_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ec2-user
          port: ${{secrets.EC2_PORT}}
          script: |
            whoami
            cd /home/ec2-user
            sudo docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
            sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mukpic-server:v1
            sudo docker-compose -f ./docker-compose.yml up -d
